layout_spectrum: 0.6995824657957816
typography_spectrum: 0.9666140880854339
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.5515616073056429
  lightness: 0.75527312423997
  saturation: 0.5762582869576013
  rhythmicContrast: 0.563774320849651
coverPrefs:
  filter: false
name: 'Machine Learning, AI'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d35ac939-7c03-4e61-b20d-ee6e2c60576c.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/baa4461f-5289-4086-a767-788fd369908b.png
purpose:
  - type: external
    label: Contact with Experts
    url: 'http://www.labsharegroup.com/'
  - type: external
    label: GitHub Repositories
    url: 'https://github.com/ZahoreczTibor?tab=repositories'
title: Machine Learning
description: AI learning evolution
author:
  name: Zahorecz Tibor
  url: 'http://www.labsharegroup.com/'
  email: tibor.zahorecz@dosell.io
navigation:
  - name: EXPERTS
    url: 'http://www.labsharegroup.com/'
    type: external
  - name: Business Architecture
    url: 'http://www.buildventure.net/'
    type: external
content: []
github: true
