layout_spectrum: 0.5674460595122327
typography_spectrum: 0.5260892513524372
color:
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
  brandStrength: 0.8495315768572473
  lightness: 0.24859832704426849
  saturation: 0.9869945460130082
  rhythmicContrast: 0.14903259857908113
coverPrefs:
  filter: false
name: 'Machine Learning, AI'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d35ac939-7c03-4e61-b20d-ee6e2c60576c.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/baa4461f-5289-4086-a767-788fd369908b.png
purpose:
  - type: external
    label: Contact with Experts
    url: 'http://www.labsharegroup.com/'
  - type: external
    label: GitHub Repositories
    url: 'https://github.com/ZahoreczTibor?tab=repositories'
title: Machine Learning
description: AI learning evolution
author:
  name: Zahorecz Tibor
  url: 'http://www.labsharegroup.com/'
  email: tibor.zahorecz@dosell.io
navigation:
  - name: EXPERTS
    url: 'http://www.labsharegroup.com/'
    type: external
  - name: Improve Product Security
    url: 'http://www.improveproductsecurity.com/'
    type: external
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/15c88d71e1237e5134fe2442590a2df3a21d0ab4.png">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/15c88d71e1237e5134fe2442590a2df3a21d0ab4.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://s3-us-west-2.amazonaws.com'
        name: .s3-us-west-2.amazonaws.com
        favicon: null
        domain: imgflo.herokuapp.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      isBasedOnUrl: >-
        https://imgflo.herokuapp.com/graph/2b2431f8e7ba7b0/fa2b8b54ecb0b7e2b52768ba79802f93/noop.png?input=https%3A%2F%2Fopenai.com%2Fassets%2Fimages%2Fopengraph%2Fog_image-1cfd63ae6b.png
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
