layout_spectrum: 0.3174326463071353
typography_spectrum: 0.9755482695040542
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.6257998176613399
  lightness: 0.5865720717533316
  saturation: 0.9811341544536708
  rhythmicContrast: 0.5533287317445963
coverPrefs:
  filter: false
name: 'Machine Learning, AI'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d35ac939-7c03-4e61-b20d-ee6e2c60576c.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/baa4461f-5289-4086-a767-788fd369908b.png
purpose:
  - type: external
    label: Contact with Experts
    url: 'http://www.labsharegroup.com/'
  - type: external
    label: GitHub Repositories
    url: 'https://github.com/ZahoreczTibor?tab=repositories'
title: Machine Learning
description: AI learning evolution
author:
  name: Zahorecz Tibor
  url: 'http://www.labsharegroup.com/'
  email: tibor.zahorecz@dosell.io
navigation:
  - name: EXPERTS
    url: 'http://www.labsharegroup.com/'
    type: external
  - name: Business Architecture
    url: 'http://www.buildventure.net/'
    type: external
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/576492cd4cbb2edd296089d3ae5a48a77f6449c3.jpg">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/576492cd4cbb2edd296089d3ae5a48a77f6449c3.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      isBasedOnUrl: >-
        https://imgflo.herokuapp.com/graph/2b2431f8e7ba7b0/850a8f357cc1eff67e9c86441d16dedb/noop.jpg?input=http%3A%2F%2Fsloanreview.mit.edu%2Fcontent%2Fuploads%2F2017%2F09%2F2017-AI-BCG-Report-Artificial-Intelligence-Business-1200x627.jpg
      keywords: []
      publisher:
        name: .s3-us-west-2.amazonaws.com
        domain: imgflo.herokuapp.com
        url: 'https://s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
