layout_spectrum: 0.7818457804649773
typography_spectrum: 0.2770512983786625
color:
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
  brandStrength: 0.5659207598033297
  lightness: 0.9536626626635984
  saturation: 0.8915095208591717
  rhythmicContrast: 0.9373300692700034
coverPrefs:
  filter: false
name: 'Machine Learning, AI'
navigation:
  - name: EXPERTS
    url: 'http://www.labsharegroup.com/'
    type: external
  - name: Business Architecture
    url: 'http://www.buildventure.net/'
    type: external
title: Machine Learning
content: []
description: learning evolution
purpose:
  - type: external
    url: 'http://www.labsharegroup.com/'
    label: Contact with Experts
  - type: external
    url: 'https://github.com/ZahoreczTibor?tab=repositories'
    label: GitHub Repositories
github: true
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d35ac939-7c03-4e61-b20d-ee6e2c60576c.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/baa4461f-5289-4086-a767-788fd369908b.png
author:
  name: Zahorecz Tibor
  email: tibor.zahorecz@dosell.io
  url: 'http://www.labsharegroup.com/'
